import tabs from "./tab.js";

function biryaniTabChange() {
    let dishDiv = document.querySelector(".dish");
    dishDiv.innerHTML = "";
    tabs.dishText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed urna eget quam dictum luctus vitae at lorem. Curabitur condimentum euismod neque vestibulum dignissim. Morbi elementum, odio vel cursus sodales, magna quam ullamcorper nulla, sed luctus orci nisl vel magna. Cras vel nunc sed sem fermentum mollis. Sed finibus odio in nibh blandit placerat. Maecenas et facilisis ligula, id egestas elit. Cras consequat, nisl at scelerisque ullamcorper, nisi purus volutpat dolor, nec lobortis ipsum sapien non orci. Nullam mauris magna, fringilla non sapien quis, vehicula condimentum mi. Duis dolor massa, aliquam eget nunc nec, mollis luctus erat. Phasellus nec nisl eget enim ullamcorper tincidunt. Nunc eu elementum nibh, quis pulvinar magna. Quisque id porta eros. Nullam facilisis turpis facilisis massa tincidunt tincidunt.");
    tabs.dishText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed urna eget quam dictum luctus vitae at lorem. Curabitur condimentum euismod neque vestibulum dignissim. Morbi elementum, odio vel cursus sodales, magna quam ullamcorper nulla, sed luctus orci nisl vel magna. Cras vel nunc sed sem fermentum mollis. Sed finibus odio in nibh blandit placerat. Maecenas et facilisis ligula, id egestas elit. Cras consequat, nisl at scelerisque ullamcorper, nisi purus volutpat dolor, nec lobortis ipsum sapien non orci. Nullam mauris magna, fringilla non sapien quis, vehicula condimentum mi. Duis dolor massa, aliquam eget nunc nec, mollis luctus erat. Phasellus nec nisl eget enim ullamcorper tincidunt. Nunc eu elementum nibh, quis pulvinar magna. Quisque id porta eros. Nullam facilisis turpis facilisis massa tincidunt tincidunt.");
    tabs.dishText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed urna eget quam dictum luctus vitae at lorem. Curabitur condimentum euismod neque vestibulum dignissim. Morbi elementum, odio vel cursus sodales, magna quam ullamcorper nulla, sed luctus orci nisl vel magna. Cras vel nunc sed sem fermentum mollis. Sed finibus odio in nibh blandit placerat. Maecenas et facilisis ligula, id egestas elit. Cras consequat, nisl at scelerisque ullamcorper, nisi purus volutpat dolor, nec lobortis ipsum sapien non orci. Nullam mauris magna, fringilla non sapien quis, vehicula condimentum mi. Duis dolor massa, aliquam eget nunc nec, mollis luctus erat. Phasellus nec nisl eget enim ullamcorper tincidunt. Nunc eu elementum nibh, quis pulvinar magna. Quisque id porta eros. Nullam facilisis turpis facilisis massa tincidunt tincidunt.");
}

function pulaoTabChange(){
    let dishDiv = document.querySelector(".dish");
    dishDiv.innerHTML = "";
    tabs.dishText("Cras a erat sed justo imperdiet molestie. Nunc tempus erat sed rutrum ornare. Aenean neque leo, aliquet at velit et, mattis varius magna. Suspendisse dignissim commodo metus, nec sagittis nunc eleifend in. Aenean ac odio eget ante semper placerat sed sit amet ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin tempus sit amet dui nec viverra. Proin sit amet sodales ipsum. Aliquam eu elit eu velit egestas ullamcorper non ut arcu. Integer finibus tellus a semper elementum. Duis iaculis id neque sed vulputate. Mauris ut tempor leo. Ut enim risus, molestie eget iaculis id, tincidunt ac purus. In nec massa diam.");
    tabs.dishText("Cras a erat sed justo imperdiet molestie. Nunc tempus erat sed rutrum ornare. Aenean neque leo, aliquet at velit et, mattis varius magna. Suspendisse dignissim commodo metus, nec sagittis nunc eleifend in. Aenean ac odio eget ante semper placerat sed sit amet ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin tempus sit amet dui nec viverra. Proin sit amet sodales ipsum. Aliquam eu elit eu velit egestas ullamcorper non ut arcu. Integer finibus tellus a semper elementum. Duis iaculis id neque sed vulputate. Mauris ut tempor leo. Ut enim risus, molestie eget iaculis id, tincidunt ac purus. In nec massa diam.");
    tabs.dishText("Cras a erat sed justo imperdiet molestie. Nunc tempus erat sed rutrum ornare. Aenean neque leo, aliquet at velit et, mattis varius magna. Suspendisse dignissim commodo metus, nec sagittis nunc eleifend in. Aenean ac odio eget ante semper placerat sed sit amet ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin tempus sit amet dui nec viverra. Proin sit amet sodales ipsum. Aliquam eu elit eu velit egestas ullamcorper non ut arcu. Integer finibus tellus a semper elementum. Duis iaculis id neque sed vulputate. Mauris ut tempor leo. Ut enim risus, molestie eget iaculis id, tincidunt ac purus. In nec massa diam.");
}

function aloomatarTabChange(){
    let dishDiv = document.querySelector(".dish");
    dishDiv.innerHTML = "";
    tabs.dishText("Fusce rhoncus tellus sit amet purus pellentesque feugiat. Aliquam sed tellus nisi. Duis blandit sem elit. Donec vulputate neque sit amet commodo tincidunt. Maecenas non tristique magna. Etiam nibh lectus, eleifend nec mi non, imperdiet consequat enim. Nulla a lobortis nulla, eget posuere lacus. Morbi ornare auctor vehicula. Donec non molestie lacus. Mauris sem augue, maximus sed placerat ut, rhoncus tristique felis. Nam vulputate convallis metus, in consectetur mauris aliquam at. Phasellus euismod risus vel tempor gravida. Vivamus at luctus turpis, sed rutrum dui. Pellentesque mi risus, molestie vitae venenatis finibus, accumsan ac quam. Donec congue id magna eget dignissim. In hac habitasse platea dictumst.");
    tabs.dishText("Cras a erat sed justo imperdiet molestie. Nunc tempus erat sed rutrum ornare. Aenean neque leo, aliquet at velit et, mattis varius magna. Suspendisse dignissim commodo metus, nec sagittis nunc eleifend in. Aenean ac odio eget ante semper placerat sed sit amet ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin tempus sit amet dui nec viverra. Proin sit amet sodales ipsum. Aliquam eu elit eu velit egestas ullamcorper non ut arcu. Integer finibus tellus a semper elementum. Duis iaculis id neque sed vulputate. Mauris ut tempor leo. Ut enim risus, molestie eget iaculis id, tincidunt ac purus. In nec massa diam.");
    tabs.dishText("Cras a erat sed justo imperdiet molestie. Nunc tempus erat sed rutrum ornare. Aenean neque leo, aliquet at velit et, mattis varius magna. Suspendisse dignissim commodo metus, nec sagittis nunc eleifend in. Aenean ac odio eget ante semper placerat sed sit amet ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin tempus sit amet dui nec viverra. Proin sit amet sodales ipsum. Aliquam eu elit eu velit egestas ullamcorper non ut arcu. Integer finibus tellus a semper elementum. Duis iaculis id neque sed vulputate. Mauris ut tempor leo. Ut enim risus, molestie eget iaculis id, tincidunt ac purus. In nec massa diam.");
}

export {
    biryaniTabChange,
    pulaoTabChange,
    aloomatarTabChange
};